version: '3'
services:
  selenoid:
    network_mode: bridge
    container_name: selenoid
    image: aerokube/selenoid:latest-release
    volumes:
      - "/home/ubuntu/docker-compose/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/ubuntu/docker-compose/config/video:/opt/selenoid/video"
      - "/home/ubuntu/docker-compose/config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/home/ubuntu/docker-compose/config/video
    command: ["-limit", "10", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4443:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
